export const ActionTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  SET_ROW_PER_PAGE: "SET_ROW_PER_PAGE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  DELETE_USER: "DELETE_USER",
  SET_FILTER: "SET_FILTER",
  SET_SELECTED_USER_DETAILS: "SET_SELECTED_USER_DETAILS",
  SET_SELECTED_USER: "SET_SELECTED_USER"
};

export const DEFAULT = {
  ROW_PER_PAGE: 3,
  CURRENT_PAGE: 0
};

export const FILTER = {
  SORT: {
    NAME: "name",
    EMAIL: "email"
  }
};
